on: [push]

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy application
        run: |
          sudo chmod 400 ac.pem
          ssh -i "ac.pem" ubuntu@ec2-35-180-87-53.eu-west-3.compute.amazonaws.com
          cd ~/web
          git checkout main
          git pull
