on: [push]

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: multiple command
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
                cd ~/web
                git checkout main
                git pull
      
